"""List optimizer (§2 decision 10, §8 Stage B).

Searches *all* tournament-legal units of a faction — not just owned models —
inside the points cap, then scores each candidate by playing it against a fixed
opponent list.

Legality enforced here (§4.8): the points cap, Legends exclusion, the
duplication limit, per-copy points tiers (a third Hellhound costs more), the
Imperial Agents dual-points-column choice, and the detachment's own DP cost.
Anything the snapshot cannot confirm is a GAP in ``data2/gaps.json`` rather
than an assumed rule.
"""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from ..rng import Rng
from ..schema import Army, ArmyUnit, Datasheet
from .run import RESULT_SCHEMA_VERSION, play_game

MAX_COPIES = 3           # duplication limit for a non-BATTLELINE datasheet
MAX_COPIES_BATTLELINE = 6


@dataclass
class Candidate:
    army: Army
    score: float = 0.0
    wins: int = 0
    games: int = 0
    vp_for: int = 0
    vp_against: int = 0

    def to_json(self) -> Dict[str, Any]:
        return {
            "name": self.army.name,
            "points": self.army.points,
            "detachment": self.army.detachment,
            "units": [
                {"datasheet": u.datasheet_id, "models": u.models} for u in self.army.units
            ],
            "score": round(self.score, 3),
            "wins": self.wins,
            "games": self.games,
            "avg_vp_for": round(self.vp_for / max(1, self.games), 2),
            "avg_vp_against": round(self.vp_against / max(1, self.games), 2),
        }


def legal_pool(data, faction: str) -> List[Datasheet]:
    """Every tournament-legal datasheet of the faction (Legends excluded)."""
    return [
        d for d in data.datasheets.values()
        if d.faction == faction and not d.legends and d.points
    ]


def cheapest_tier(ds: Datasheet, column: str = "army_faction"):
    tiers = [t for t in ds.points if t.column == column]
    if not tiers:
        return None
    return min(tiers, key=lambda t: t.points)


def copy_cost(ds: Datasheet, models: int, copy_index: int, column: str) -> Optional[int]:
    return ds.cost(models, copy_index=copy_index, column=column)


def generate_candidate(data, faction: str, detachment: str, cap: int, rng: Rng,
                       index: int) -> Optional[Army]:
    """One legal roster, sampled from the whole legal pool."""
    pool = legal_pool(data, faction)
    if not pool:
        return None
    det = data.detachments.get(detachment)
    dp_budget = data.meta.get("dp_budget", {}).get(str(cap))
    column = "army_faction"

    characters = [d for d in pool if "CHARACTER" in [k.upper() for k in d.keywords]]
    battleline = [d for d in pool if "BATTLELINE" in [k.upper() for k in d.keywords]]
    others = [d for d in pool if d not in characters and d not in battleline]

    units: List[ArmyUnit] = []
    counts: Dict[str, int] = {}
    total = 0

    def try_add(ds: Datasheet, warlord: bool = False) -> bool:
        nonlocal total
        tier = cheapest_tier(ds, column)
        if tier is None:
            return False
        copy_index = counts.get(ds.id, 0) + 1
        limit = MAX_COPIES_BATTLELINE if ds in battleline else MAX_COPIES
        if copy_index > limit:
            return False
        cost = copy_cost(ds, tier.models, copy_index, column)
        if cost is None or total + cost > cap:
            return False
        counts[ds.id] = copy_index
        units.append(ArmyUnit(datasheet_id=ds.id, models=tier.models, warlord=warlord,
                              key=str(len(units))))
        total += cost
        return True

    if characters:
        try_add(rng.choice(characters), warlord=True)
    # a spine of battleline, then whatever fits
    for _ in range(12):
        if total > cap * 0.55 or not battleline:
            break
        try_add(rng.choice(battleline))
    for _ in range(40):
        if total > cap * 0.97:
            break
        bucket = others or battleline
        if not bucket:
            break
        try_add(rng.choice(bucket))

    if not units:
        return None
    return Army(
        name=f"candidate-{index:03d}",
        faction=faction,
        detachments=[detachment] if detachment else [],
        units=units,
        battle_size=cap,
        points=total,
        notes=[f"generated by the optimizer from {len(pool)} legal datasheets"],
    )


def run_optimizer(
    data,
    faction: str,
    detachment: str,
    opponent: Army,
    candidates: int = 20,
    games: int = 4,
    seed: int = 1,
    battle_size: int = 1000,
    out_dir: str = "results",
    agent: str = "heuristic",
) -> Dict[str, Any]:
    rng = Rng(seed)
    if not detachment:
        options = [d.id for d in data.detachments.values() if d.faction == faction]
        detachment = options[0] if options else ""

    scored: List[Candidate] = []
    started = time.time()
    for i in range(candidates):
        army = generate_candidate(data, faction, detachment, battle_size, rng, i)
        if army is None:
            continue
        cand = Candidate(army=army)
        for g in range(games):
            game_seed = seed * 1000 + i * 10 + g
            res, _ = play_game(data, army, opponent, game_seed, agent, agent, battle_size)
            cand.games += 1
            cand.vp_for += res.vp[0]
            cand.vp_against += res.vp[1]
            if res.winner == 0:
                cand.wins += 1
        cand.score = (cand.vp_for - cand.vp_against) / max(1, cand.games)
        scored.append(cand)

    scored.sort(key=lambda c: -c.score)
    summary = {
        "result_schema_version": RESULT_SCHEMA_VERSION,
        "kind": "optimizer",
        "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "config": {
            "faction": faction, "detachment": detachment, "opponent": opponent.name,
            "candidates": candidates, "games_per_candidate": games,
            "battle_size": battle_size, "seed": seed, "agent": agent,
        },
        "pool_size": len(legal_pool(data, faction)),
        "duration_s": round(time.time() - started, 1),
        "leaderboard": [c.to_json() for c in scored],
    }
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "optimizer.json"), "w", encoding="utf-8") as fh:
        json.dump(summary, fh, indent=1)
    return summary
